makemigrations:
	sudo docker-compose run --rm django python3 manage.py makemigrations
migrate:
	sudo docker-compose run --rm django python3 manage.py migrate
createsuperuser:
	sudo docker-compose run --rm django python3 manage.py createsuperuser
